name: CI & Release

on:
  push:
    branches: [develop, stage, main, master]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npm run lint

      - run: npm run build

      - run: npm run test

      - run: npm run publint

      - run: npm run attw

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release-github:
    name: Release (GitHub Packages)
    needs: ci
    if: endsWith(github.ref, '/main')
    uses: bear2b/.github-private/.github/workflows/node-release-github.yml@master
    permissions:
      contents: write
      issues: write
      packages: write
      pull-requests: write

  # release-npm:
  #   name: Release (npm)
  #   needs: ci
  #   if: endsWith(github.ref, '/example')
  #   uses: bear2b/.github-private/.github/workflows/node-release-npm.yml@master
  #   permissions:
  #     contents: write
  #     issues: write
  #     packages: write
  #     pull-requests: write
  #   secrets:
  #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  docs:
    name: Documentation
    needs: ci
    if: endsWith(github.ref, '/develop')
    uses: bear2b/.github-private/.github/workflows/node-deploy-docs.yml@master
    permissions:
      pages: write
      id-token: write
